/**
 * Builds the v3 character pack: one spritesheet, one metadata JSON and one portrait per character.
 *
 * Run with `node scripts/gen-characters/index.mjs [--out <dir>] [--preview <file>]`. The output is
 * COMMITTED, not built on demand — the browser loads these as static assets and the project ships
 * no image toolchain. Regenerating is how you iterate on the art here; refining it by hand in
 * Aseprite and leaving the generator behind is an equally valid end state, which is why the
 * metadata is written from the same clip table the drawing uses and never typed twice.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodePng } from './png.mjs';
import { blit, Frame, frameToRgba } from './pixel.mjs';
import { CHARACTERS } from './palette.mjs';
import { FRAME_SIZE, ORIGIN, renderFrame } from './body.mjs';
import { CLIPS, FRAMES } from './poses.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const SHEET_W = FRAME_SIZE * FRAMES;
const SHEET_H = FRAME_SIZE * CLIPS.length;

function buildSheet(palette) {
  const sheet = new Frame(SHEET_W, SHEET_H);
  for (const clip of CLIPS) {
    for (let t = 0; t < FRAMES; t++) {
      blit(sheet, renderFrame(palette, clip.pose(t)), t * FRAME_SIZE, clip.row * FRAME_SIZE);
    }
  }
  return sheet;
}

/** Head-and-shoulders crop of the resting frame, nearest-neighbour upscaled. Portraits are for
 * panels and tooltips only (guide section 20), never for the scene. */
function buildPortrait(palette, size = 256) {
  const source = renderFrame(palette, CLIPS[0].pose(0));
  const crop = 32;
  const cropX = ORIGIN.x - crop / 2;
  const cropY = 2;
  const factor = size / crop;
  const out = new Frame(size, size);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      out.set(x, y, source.get(cropX + Math.floor(x / factor), cropY + Math.floor(y / factor)));
    }
  }
  return out;
}

function buildMeta(id, palette) {
  const animations = {};
  for (const clip of CLIPS) {
    animations[clip.action] ??= {};
    animations[clip.action][clip.direction] = {
      row: clip.row,
      frames: FRAMES,
      fps: clip.fps,
      loop: clip.loop,
      mirrorForLeft: clip.direction === 'side',
    };
  }

  return {
    schemaVersion: 3,
    id,
    displayName: palette.displayName,
    role: palette.role,
    image: `${id}_spritesheet_v3.png`,
    frameWidth: FRAME_SIZE,
    frameHeight: FRAME_SIZE,
    sheetWidth: SHEET_W,
    sheetHeight: SHEET_H,
    origin: { x: ORIGIN.x, y: ORIGIN.y },
    // Feet-sized, not body-sized, so a head may overlap a desk without blocking the floor.
    hitbox: { offsetX: -13, offsetY: -14, width: 26, height: 14 },
    defaultScale: 2,
    defaultDirection: 'down',
    sideFaces: 'right',
    animations,
    fallbackDirections: { work: 'up', typing: 'up', celebrate: 'down', sit: 'down' },
    runtimeNotes: [
      'Furniture-free sprites. Desks, laptops and chairs belong to the environment.',
      'Render left direction by horizontally mirroring side frames.',
      'Generated by scripts/gen-characters; regenerate rather than hand-editing unless the pack has been taken over in Aseprite.',
    ],
  };
}

/** One PNG with every character's every clip, for eyeballing a generation without loading the app. */
function buildPreview(sheets) {
  const gap = 8;
  const preview = new Frame(sheets.length * (SHEET_W + gap) - gap, SHEET_H);
  sheets.forEach((sheet, i) => blit(preview, sheet, i * (SHEET_W + gap), 0));
  return preview;
}

function writeFrame(path, frame) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, encodePng(frame.width, frame.height, frameToRgba(frame)));
}

function main() {
  const args = process.argv.slice(2);
  const outIndex = args.indexOf('--out');
  const outDir = resolve(outIndex >= 0 ? args[outIndex + 1] : resolve(HERE, '../../public/characters'));
  const previewIndex = args.indexOf('--preview');

  const sheets = [];
  const manifest = { format: 'pixel-office-v3', version: 3, note: "Paths are relative to this file's own served directory (/characters), not to the source pack layout.", characters: {} };

  for (const [id, palette] of Object.entries(CHARACTERS)) {
    const sheet = buildSheet(palette);
    sheets.push(sheet);
    writeFrame(resolve(outDir, id, `${id}_spritesheet_v3.png`), sheet);
    writeFrame(resolve(outDir, id, `${id}_portrait_v3.png`), buildPortrait(palette));
    const meta = buildMeta(id, palette);
    mkdirSync(resolve(outDir, id), { recursive: true });
    writeFileSync(resolve(outDir, id, `${id}.json`), `${JSON.stringify(meta, null, 2)}\n`);
    manifest.characters[id] = {
      displayName: palette.displayName,
      role: palette.role,
      metadata: `${id}/${id}.json`,
      spritesheet: `${id}/${id}_spritesheet_v3.png`,
      portrait: `${id}/${id}_portrait_v3.png`,
    };
    console.log(`${id}: ${SHEET_W}x${SHEET_H} sheet, ${CLIPS.length} clips x ${FRAMES} frames`);
  }

  writeFileSync(resolve(outDir, 'characters_manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);

  if (previewIndex >= 0) {
    writeFrame(resolve(args[previewIndex + 1]), buildPreview(sheets));
    console.log(`preview: ${args[previewIndex + 1]}`);
  }
}

main();
